name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - master # Replace with your main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or your preferred Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Adjust to your build directory
          publish_branch: gh-pages # The branch where GitHub Pages will be deployed

      - name: Cleanup
        run: rm -rf node_modules # Remove node_modules after the build
